site_name: foodcourt
site_description: Share and sell authentic food
repo_url: https://github.com/djanmamur/foodcourt
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/djanmamur">djanmamur</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
